// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbf3VoFbADGWRWBKBcJerhdhVlOBLoFU0',
    appId: '1:219907708420:web:ec01b91442924d02c00751',
    messagingSenderId: '219907708420',
    projectId: 'yourgoal-55b5c',
    authDomain: 'yourgoal-55b5c.firebaseapp.com',
    databaseURL: 'https://yourgoal-55b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourgoal-55b5c.firebasestorage.app',
    measurementId: 'G-J26DJ6FR3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxX-_VIMki4SEn2ePBqeOn24T9yHWdYsw',
    appId: '1:219907708420:android:7421511a2c55f350c00751',
    messagingSenderId: '219907708420',
    projectId: 'yourgoal-55b5c',
    databaseURL: 'https://yourgoal-55b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourgoal-55b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhstBPbrClUM8VGAbNoNc3V_JzUTrNP5c',
    appId: '1:219907708420:ios:4aeb06540cb1fb4ec00751',
    messagingSenderId: '219907708420',
    projectId: 'yourgoal-55b5c',
    databaseURL: 'https://yourgoal-55b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourgoal-55b5c.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhstBPbrClUM8VGAbNoNc3V_JzUTrNP5c',
    appId: '1:219907708420:ios:4aeb06540cb1fb4ec00751',
    messagingSenderId: '219907708420',
    projectId: 'yourgoal-55b5c',
    databaseURL: 'https://yourgoal-55b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourgoal-55b5c.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbf3VoFbADGWRWBKBcJerhdhVlOBLoFU0',
    appId: '1:219907708420:web:7e30d0e935b201bec00751',
    messagingSenderId: '219907708420',
    projectId: 'yourgoal-55b5c',
    authDomain: 'yourgoal-55b5c.firebaseapp.com',
    databaseURL: 'https://yourgoal-55b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourgoal-55b5c.firebasestorage.app',
    measurementId: 'G-XL1B4NHWVC',
  );
}
